name = "eensy_dev_tools"
version = "0.3.1"
description = "Dev Tools for Eensy (Gleam framework for microprocessor-based embedded systems)."
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"
spinner = "~> 1.1"
gleam_package_interface = ">= 2.0.0 and < 3.0.0"
gleam_otp = ">= 0.9.0 and < 1.0.0"
tom = ">= 1.0.1 and < 2.0.0"
gleam_community_ansi = ">= 1.4.1 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
glint = ">= 1.0.1 and < 2.0.0"
atomvm_packbeam = ">= 0.7.2 and < 1.0.0"
# uf2tool = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
